# https://github.com/lando/lando/issues/1991#issuecomment-967760888
name: pgadmin-test

services:
  postgres:
    type: postgres
    creds:
      database: learning
      user: postgres
      password: password
  
  pgadmin:
    type: lando
    api: 3
    scanner: false # PgAdmin returns a 401 with a redirection that Lando doesn't like
    ssl: true
    services:
      image: dpage/pgadmin4
      command: /entrypoint.sh
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "127.0.0.1::80"

proxy:
  pgadmin:
    - pgadmin-test.lndo.site
